"""Defines the evaluation rubric items from PEP 8001."""

# Core items are essential for a good README.
CORE = [
    "CLARITY_OF_PURPOSE",
    "QUICKSTART_INSTALL",
    "HELLO_WORLD_EXAMPLE",
    "VISUAL_DEMONSTRATION",
    "CONTRIBUTION_GATEWAY",
    "DEVELOPMENT_SETUP",
    "LICENSE_CLARITY",
    "PROJECT_HEALTH_BADGES",
]

# Extra credit items represent documentation maturity and polish.
EXTRA = [
    "PRIOR_ART_COMPARISON",
    "DESIGN_RATIONALE",
    "TUTORIAL_OR_WALKTHROUGH",
    "REAL_WORLD_USAGE",
    "PERFORMANCE_SECTION",
    "CONTAINER_IMAGE_LINK",
    "SUPPORT_MATRIX",
    "I18N_SUPPORT_INFO",
    "ACCESSIBILITY_DISCUSSION",
    "ETHICAL_STATEMENT",
    "CHANGELOG_LINK",
    "ROADMAP_OR_VISION",
    "COMMUNITY_GUIDELINES",
    "FUNDING_INFORMATION",
    "ACKNOWLEDGMENTS",
    "CONFIGURATION_EXAMPLES",
    "API_REFERENCE_LINK",
    "ARCHITECTURE_OVERVIEW",
    "DEPENDENCY_POLICY",
    "REPRODUCIBILITY_NOTES",
    "SECURITY_POLICY_LINK",
]