site_name: "troml_dev_status"
site_url: "https://troml-dev-status.readthedocs.io/"
site_author: "Matthew Dean Martin <matthewdeanmartin@gmail.com>"
site_description: "Documentation of troml_dev_status, a tool for inferring the trove classifier for development status."

repo_url: "https://github.com/matthewdeanmartin/troml_dev_status"

theme:
  name: readthedocs
  features:
    - navigation.footer

edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - codehilite
  - toc:
      permalink: true

nav:
    - 'Home': 'index.md'
    - 'Installation': 'installation.md'
    - 'Usage': 'usage.md'
    - 'Core Concepts': 'concepts.md'
    - 'The Rubric (All Checks)': 'rubric.md'
    - 'How Status is Determined': 'status_mapping.md'
    - 'Using as a Library': 'library_api.md'
    - 'Prior Art': 'prior_art.md'
    - 'Reference':
        - 'Full PEP': 'PEP.md'